http:
  routers:
    traefik:
      rule: "Host(`traefik.alls.dev`)"
      service: "api@internal"
      tls:
        domains:
          - main: "alls.dev"
            sans:
              - "*.alls.dev"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"