# Node.js Project Template
# Copy this to your project's docker-compose.yml and customize as needed

version: '3.9'

services:
  app:
    image: node:18-alpine
    command: npm run dev
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeapp.rule=Host(`nodeapp.web.localhost`)"
      - "traefik.http.routers.nodeapp.tls=true"
      - "traefik.http.services.nodeapp.loadbalancer.server.port=3000"
    networks:
      - traefik

  # Optional: Redis for sessions/cache
  redis:
    image: redis:7-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.web.localhost`)"
      - "traefik.http.routers.redis.tls=true"
      - "traefik.http.services.redis.loadbalancer.server.port=6379"
    networks:
      - traefik

networks:
  traefik:
    external: true

