# Static Site Template (Nginx)
# Copy this to your project's docker-compose.yml and customize as needed

version: '3.9'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./public:/usr/share/nginx/html:ro
      # Optional: custom nginx config
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staticsite.rule=Host(`staticsite.web.localhost`)"
      - "traefik.http.routers.staticsite.tls=true"
      - "traefik.http.services.staticsite.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true

